# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=88, verbose_name='姓名')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('email', models.CharField(max_length=255, verbose_name='邮箱')),
                ('sex', models.SmallIntegerField(choices=[(0, 'female'), (1, 'man'), (2, 'unknown')], verbose_name='性别')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='居住地')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='就职公司')),
                ('college', models.CharField(blank=True, max_length=80, null=True, verbose_name='毕业院校')),
                ('avatar', models.CharField(blank=True, default='default', max_length=255, verbose_name='头像')),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'verbose_name': '用户信息',
                'db_table': 'infos',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('permission', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': '用户角色',
                'verbose_name': '用户角色',
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='info',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='role_info', to='user_auth.Role', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='info',
            name='temp_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_role_info', to='user_auth.Role', verbose_name='临时角色'),
        ),
        migrations.AddField(
            model_name='info',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL),
        ),
    ]
