# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='info',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, '女'), (1, '男'), (2, '不明')], verbose_name='性别'),
        ),
    ]
