# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-02 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': '文章类型',
                'verbose_name': '文章类型',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('email', models.CharField(max_length=255, verbose_name='邮箱')),
                ('sex', models.SmallIntegerField(blank=True, null=True, verbose_name='性别')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='居住地')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='就职公司')),
                ('college', models.CharField(max_length=80, verbose_name='毕业院校')),
                ('avatar', models.CharField(max_length=255, verbose_name='头像')),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'verbose_name': '用户信息',
                'db_table': 'infos',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('excerpt', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_posts', to='blog.Category')),
            ],
            options={
                'verbose_name_plural': '文章',
                'verbose_name': '文章',
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('permission', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': '用户角色',
                'verbose_name': '用户角色',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': '文章标签',
                'verbose_name': '文章标签',
                'db_table': 'tags',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='tag_posts', to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='info',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_info', to='blog.Role', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='info',
            name='temp_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_role_info', to='blog.Role', verbose_name='临时角色'),
        ),
    ]
