# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-06 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=88)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'friendlinks',
                'verbose_name_plural': '友情链接',
                'verbose_name': '友情链接',
            },
        ),
    ]
