# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-06 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='img',
            field=models.URLField(default=1, help_text='站点logo图地址'),
            preserve_default=False,
        ),
    ]
