# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20171015_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
