# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20171015_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '博文评论', 'verbose_name_plural': '博文评论'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '博客文章', 'verbose_name_plural': '博客文章'},
        ),
    ]
