# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-17 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_comment_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[(0, '代办')], max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_notes', to='blog.Category')),
                ('tags', models.ManyToManyField(related_name='tag_notes', to='blog.Tag')),
            ],
            options={
                'db_table': 'notes',
                'verbose_name_plural': '个人笔记',
                'verbose_name': '个人笔记',
                'ordering': ['-created_time'],
            },
        ),
    ]
