# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-17 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('0', '代办')], max_length=1),
        ),
    ]
