# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180217_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='update_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='update_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_time',
            field=models.DateTimeField(),
        ),
    ]
