# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-17 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180220_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='excerpt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.CharField(default='https://s1.ax1x.com/2018/03/12/9f13Hf.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
